version: 2
cli:
    server: https://app.fossa.com
    fetcher: custom
    project: appkit
analyze:
    modules:
        -   name: github.com/sagikazarmark/appkit
            type: go
            target: github.com/sagikazarmark/appkit
            strategy: gomodules
            path: .
            options:
                allow-unresolved: true
