linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: github.com/sagikazarmark/appkit

linters:
    enable-all: true
    disable:
        - funlen
        - wsl

service:
    golangci-lint-version: 1.21.x
