linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: github.com/sagikazarmark/appkit

linters:
    presets:
        - bugs
        - unused
        - format
        - import
    disable:
        - noctx
